### ISSUE TITLE
Pipes within item_id / item_sku in the items array lead to additional columns / column mismatch in product strings

### ISSUE THREAD

**Issue by 00kennedyp** [stape-io/awin-tag#8]
Firstly thanks for building out this template it been really great to us and saved me a lot of time. 

I have a issue with the product level tracking in the template due to the fact that our business include a pipe string of our component for a item_id  For example  P123|A123|D123.   The replace method of the code does not encode or replace | leading to additional column in the product level tracking.  

I know this is an edge case issues, and I tried to fix this issue myself with the following changes to the code but it does not appear to be working 

I also dont see any console logs from your template even when in debug mode.  Could not work out why. 

Any help would be amazing.

```
const productRow =
        'AW:P|{{advertiserId}}|{{orderReference}}|{{productId}}|{{productName}}|{{productItemPrice}}|{{productQuantity}}|{{productSku}}|{{commissionGroupCode}}|{{productCategory}}';
      if (getType(items) === 'array') {
        items.forEach((item, index) => {
          let item_id = item.item_id || '';
          item_id.replace('|','/');
          
          let value = productRow.replace(
            '{{advertiserId}}',
            item.advertiser_id || data.advertiserId || ''
          );
          value = value.replace(
            '{{orderReference}}',
            item.order_reference || eventData.transaction_id || ''
          );
          value = value.replace('{{productId}}', item_id || '');
          value = value.replace('{{productName}}', item.item_name || '');
          value = value.replace(
            '{{productItemPrice}}',
            getPriceString(item.price)
          );
          value = value.replace('{{productQuantity}}', item.quantity || '');
          value = value.replace(
            '{{productSku}}',
            item.item_sku || item_id || ''
          );
          value = value.replace(
            '{{commissionGroupCode}}',
            item.commission_group_code || 'DEFAULT'
          );
          value = value.replace(
            '{{productCategory}}',
            item.item_category || ''
          );
          requestUrl = requestUrl + '&bd[' + index + ']=' + value;
        });
      }
```

**Comment by Bukashk0zzz** [comment]
Hi,

Thanks for reporting this issue. 
We added this issue to our internal backlog.
Hope to fix it to the end of the next week.

**Comment by 00kennedyp** [comment]
Hi Fixed this myself in the end.  Realised Sandbox JS does not support ReplaceAll function so ended up using Regex Replace instead.  

Our new code that works 

[awin stape-io.txt](https://github.com/stape-io/awin-tag/files/14184713/awin.stape-io.txt)
