### ISSUE TITLE
AWIN Consent Information

### ISSUE THREAD

**Issue by christophweihrich** [stape-io/awin-tag#9]
hey guys,
regarding this https://wiki.awin.com/index.php/Consent_Frameworks_for_Advertisers about consent information. please check if there is an update necessary for your template. 
in our usecase a had to implement it on client side. 
please let us know

**Comment by Bukashk0zzz** [comment]
Thanks for bringing this to my attention. We will check this.

**Comment by kHorozhanov** [comment]
Hi @christophweihrich!

1. The link you’ve shared is for client-side Awin tracking
2. Consent is not by default available on the server container; therefore, the expectation is you control when your tag should or should not fire explicitly
3. We plan to add optional consent checks to our tag assortment. I believe the AWIN tag will eventually be part of that, too
